### ISSUE TITLE
during PrimeBlob Gcode => unhandled exception

### ISSUE THREAD

**Issue by nicedevil007** [Rat-OS/RatOS#45]
I'm using the primeblob for start gcode without any changes and I get an error from time to time about an unhandled exception.

```
Stats 525740.0: gcodein=0  mcu: mcu_awake=0.295 mcu_task_avg=0.000137 mcu_task_stddev=0.000000 bytes_write=6312248 bytes_read=1159062 bytes_retransmit=9 bytes_invalid=0 send_seq=151190 receive_seq=151190 retransmit_seq=2 srtt=0.001 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=179999926 Octopus: temp=34.7 raspberry_pi: temp=33.1 sd_pos=43709 heater_bed: target=68 temp=68.3 pwm=0.039 sysload=1.09 cputime=27525.155 memavail=3384124 print_time=828.586 buffer_time=2.709 print_stall=0 extruder: target=215 temp=214.9 pwm=0.248
b'Got EOF when reading from device'
Stats 525741.0: gcodein=0  mcu: mcu_awake=0.295 mcu_task_avg=0.000137 mcu_task_stddev=0.000000 bytes_write=6313486 bytes_read=1159260 bytes_retransmit=1303 bytes_invalid=0 send_seq=151220 receive_seq=151208 retransmit_seq=151220 srtt=0.001 rttvar=0.001 rto=0.200 ready_bytes=54 stalled_bytes=96 freq=179999929 Octopus: temp=34.7 raspberry_pi: temp=33.6 sd_pos=43709 heater_bed: target=68 temp=68.3 pwm=0.039 sysload=1.09 cputime=27525.301 memavail=3383920 print_time=830.128 buffer_time=3.251 print_stall=0 extruder: target=215 temp=214.9 pwm=0.248
Stats 525742.0: gcodein=0  mcu: mcu_awake=0.295 mcu_task_avg=0.000137 mcu_task_stddev=0.000000 bytes_write=6313486 bytes_read=1159260 bytes_retransmit=1303 bytes_invalid=0 send_seq=151220 receive_seq=151208 retransmit_seq=151220 srtt=0.001 rttvar=0.001 rto=0.200 ready_bytes=54 stalled_bytes=97 freq=179999929 Octopus: temp=34.7 raspberry_pi: temp=34.6 sd_pos=43709 heater_bed: target=68 temp=68.3 pwm=0.039 sysload=1.09 cputime=27525.432 memavail=3383928 print_time=830.128 buffer_time=2.250 print_stall=0 extruder: target=215 temp=214.9 pwm=0.248
Stats 525743.0: gcodein=0  mcu: mcu_awake=0.295 mcu_task_avg=0.000137 mcu_task_stddev=0.000000 bytes_write=6313486 bytes_read=1159260 bytes_retransmit=1303 bytes_invalid=0 send_seq=151220 receive_seq=151208 retransmit_seq=151220 srtt=0.001 rttvar=0.001 rto=0.200 ready_bytes=54 stalled_bytes=242 freq=179999929 Octopus: temp=34.7 raspberry_pi: temp=32.6 sd_pos=43709 heater_bed: target=68 temp=68.3 pwm=0.039 sysload=1.08 cputime=27525.597 memavail=3383928 print_time=831.671 buffer_time=2.792 print_stall=0 extruder: target=215 temp=214.9 pwm=0.248
Stats 525744.0: gcodein=0  mcu: mcu_awake=0.295 mcu_task_avg=0.000137 mcu_task_stddev=0.000000 bytes_write=6313486 bytes_read=1159260 bytes_retransmit=1303 bytes_invalid=0 send_seq=151220 receive_seq=151208 retransmit_seq=151220 srtt=0.001 rttvar=0.001 rto=0.200 ready_bytes=54 stalled_bytes=387 freq=179999929 Octopus: temp=34.7 raspberry_pi: temp=33.1 sd_pos=43709 heater_bed: target=68 temp=68.3 pwm=0.039 sysload=1.08 cputime=27525.758 memavail=3383928 print_time=833.214 buffer_time=3.334 print_stall=0 extruder: target=215 temp=214.9 pwm=0.248
Stats 525745.0: gcodein=0  mcu: mcu_awake=0.295 mcu_task_avg=0.000137 mcu_task_stddev=0.000000 bytes_write=6313486 bytes_read=1159260 bytes_retransmit=1303 bytes_invalid=0 send_seq=151220 receive_seq=151208 retransmit_seq=151220 srtt=0.001 rttvar=0.001 rto=0.200 ready_bytes=54 stalled_bytes=388 freq=179999929 Octopus: temp=34.7 raspberry_pi: temp=32.6 sd_pos=43709 heater_bed: target=68 temp=68.3 pwm=0.039 sysload=1.08 cputime=27525.919 memavail=3384124 print_time=833.214 buffer_time=2.333 print_stall=0 extruder: target=215 temp=214.9 pwm=0.248
Unhandled exception during run
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 217, in run
    self.reactor.run()
  File "/home/pi/klipper/klippy/reactor.py", line 292, in run
    g_next.switch()
  File "/home/pi/klipper/klippy/reactor.py", line 340, in _dispatch_loop
    timeout = self._check_timers(eventtime, busy)
  File "/home/pi/klipper/klippy/reactor.py", line 163, in _check_timers
    self._next_timer = min(self._next_timer, waketime)
RecursionError: maximum recursion depth exceeded in comparison
Transition to shutdown state: Unhandled exception during run
Dumping gcode input 0 blocks
Dumping 20 requests for client 3045709136
```

On a restart attempt I can find something like this:

```
[Kugel_Kugelhalter_0.2mm_PLA_11m.zip](https://github.com/Rat-OS/RatOS/files/10097780/Kugel_Kugelhalter_0.2mm_PLA_11m.zip)

mcu 'mcu': Starting serial connect
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/btt-octopus-11: [Errno 2] No such file or directory: '/dev/btt-octopus-11'
webhooks client 3037072720: New connection
webhooks client 3037072720: Client info {'program': 'Moonraker', 'version': 'v0.7.1-775-gb67a08a'}
```

Because it is not finding any serialboard then, I tryed a bit in the shell of my raspberry pi:

```
root@vcore3:~# ls /dev/serial/by-id/usb-Klipper_stm32f446xx_btt-octopus-11-if00
/dev/serial/by-id/usb-Klipper_stm32f446xx_btt-octopus-11-if00
root@vcore3:~# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 1d50:614e OpenMoko, Inc.
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

That is looking absolutly ok for me. So now I'm a bit lost on how to find the problem. I will open a 2nd issue on klipper repo because I think it is not RatOS 2.0 related, isn't it?

EDIT: I tryed to reslice my file and then it was printing. Maybe something related to prusaslicer then.... mhhhh

**Comment by miklschmidt** [comment]
Not sure what caused that, i'd assume something went wrong on your octopus. Make sure it's powered via 24V and that you've removed the USB power jumper.
